{{- if .Values.server.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-server
  labels:
    {{- include "airbyte.labels" . | nindent 4 }}
    {{- if .Values.server.extraLabels }}
    {{ toYaml (mergeOverwrite .Values.server.extraLabels .Values.global.extraLabels) | nindent 4 }}
    {{- end }}
  annotations:
    {{ toYaml .Values.server.annotations | nindent 4 }}